version: '3'

networks:
  reverse-proxy:
    external: true

services:
  vikunja:
    image: vikunja/vikunja
    networks:
      - reverse-proxy
    environment:
      PUID: 99
      PGID: 100
      VIKUNJA_SERVICE_PUBLICURL: https://task.actuary.dev
      VIKUNJA_DATABASE_HOST: unraid.lan
      VIKUNJA_DATABASE_PASSWORD: postgres_password
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: postgres_user
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: test
      VIKUNJA_REDIS_ENABLED: 1
      VIKUNJA_REDIS_HOST: 'unraid.lan:6379'
      VIKUNJA_CACHE_ENABLED: 1
      VIKUNJA_CACHE_TYPE: redis
    ports:
      - 3456:3456
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.task.rule=Host(`task.actuary.dev`)"
        - "traefik.http.routers.task.entrypoints=websecure"
        - "traefik.http.routers.task.service=task"
        - "traefik.http.routers.task.tls.certresolver=myresolver"
        - "traefik.http.services.task.loadbalancer.server.port=3456"
        ## Middlewares
        - "traefik.http.routers.task.middlewares=middlewares-authentik@file"
    volumes:
      - /mnt/user/docker/volumes/vikunja:/app/vikunja/files
